# Configuration API Platform
api_platform:
  title: 'Kickstarter API'
  description: 'API du projet Symfony Kickstarter'
  version: '1.0.0'

  # Formats de reponse
  formats:
    jsonld: ['application/ld+json']
    json: ['application/json']

  # Documentation
  docs_formats:
    jsonld: ['application/ld+json']
    jsonopenapi: ['application/vnd.openapi+json']
    html: ['text/html']

  defaults:
    stateless: true
    cache_headers:
      vary: ['Content-Type', 'Authorization', 'Origin']
    extra_properties:
      standard_put: true
      rfc_7807_compliant_errors: true
    pagination_items_per_page: 30
    pagination_client_items_per_page: true
    pagination_maximum_items_per_page: 100

  # Mapping des entites
  mapping:
    paths: ['%kernel.project_dir%/src/Entity']

  # Patch avec merge
  patch_formats:
    json: ['application/merge-patch+json']

  # Activer la documentation OpenAPI
  enable_docs: true
