# Configuration CORS (Nelmio)
nelmio_cors:
  defaults:
    origin_regex: true
    allow_origin: ['^https?://localhost(:[0-9]+)?$']
    allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
    allow_headers: ['Content-Type', 'Authorization']
    expose_headers: ['Link']
    max_age: 3600
  paths:
    '^/api/':
      allow_origin: ['^https?://localhost(:[0-9]+)?$']
      allow_headers: ['Content-Type', 'Authorization', 'Accept']
      allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
      max_age: 3600
