<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * V0.6 : RBAC (permissions, groupes), OAuth (providers), 2FA (TOTP), Messenger.
 */
final class Version20260327000420 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'V0.6 - Permissions RBAC, OAuth providers, 2FA TOTP, table messenger_messages';
    }

    public function up(Schema $schema): void
    {
        // Table des permissions RBAC
        $this->addSql('CREATE TABLE permission (id UUID NOT NULL, name VARCHAR(100) NOT NULL, description VARCHAR(255) NOT NULL, category VARCHAR(50) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E04992AA5E237E06 ON permission (name)');

        // Table des groupes de permissions
        $this->addSql('CREATE TABLE permission_group (id UUID NOT NULL, name VARCHAR(100) NOT NULL, description VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BB4729B65E237E06 ON permission_group (name)');

        // Table de liaison permission_group <-> permission
        $this->addSql('CREATE TABLE permission_group_permission (permission_group_id UUID NOT NULL, permission_id UUID NOT NULL, PRIMARY KEY (permission_group_id, permission_id))');
        $this->addSql('CREATE INDEX IDX_B61B5A37B6C0CF1 ON permission_group_permission (permission_group_id)');
        $this->addSql('CREATE INDEX IDX_B61B5A37FED90CCA ON permission_group_permission (permission_id)');
        $this->addSql('ALTER TABLE permission_group_permission ADD CONSTRAINT FK_B61B5A37B6C0CF1 FOREIGN KEY (permission_group_id) REFERENCES permission_group (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE permission_group_permission ADD CONSTRAINT FK_B61B5A37FED90CCA FOREIGN KEY (permission_id) REFERENCES permission (id) ON DELETE CASCADE');

        // Table de liaison user <-> permission_group
        $this->addSql('CREATE TABLE user_permission_group (user_id UUID NOT NULL, permission_group_id UUID NOT NULL, PRIMARY KEY (user_id, permission_group_id))');
        $this->addSql('CREATE INDEX IDX_C6526B6BA76ED395 ON user_permission_group (user_id)');
        $this->addSql('CREATE INDEX IDX_C6526B6BB6C0CF1 ON user_permission_group (permission_group_id)');
        $this->addSql('ALTER TABLE user_permission_group ADD CONSTRAINT FK_C6526B6BA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_permission_group ADD CONSTRAINT FK_C6526B6BB6C0CF1 FOREIGN KEY (permission_group_id) REFERENCES permission_group (id) ON DELETE CASCADE');

        // Table OAuth providers
        $this->addSql('CREATE TABLE user_oauth_provider (id UUID NOT NULL, provider VARCHAR(30) NOT NULL, provider_user_id VARCHAR(255) NOT NULL, access_token VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D93D2FD9A76ED395 ON user_oauth_provider (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_oauth_provider_user ON user_oauth_provider (provider, provider_user_id)');
        $this->addSql('ALTER TABLE user_oauth_provider ADD CONSTRAINT FK_D93D2FD9A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');

        // Table Messenger (transport Doctrine)
        $this->addSql('CREATE TABLE IF NOT EXISTS messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');

        // Colonnes 2FA sur la table user
        $this->addSql('ALTER TABLE "user" ADD totp_secret VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD is_two_factor_enabled BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE "user" ADD backup_codes JSON DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE permission_group_permission DROP CONSTRAINT FK_B61B5A37B6C0CF1');
        $this->addSql('ALTER TABLE permission_group_permission DROP CONSTRAINT FK_B61B5A37FED90CCA');
        $this->addSql('ALTER TABLE user_permission_group DROP CONSTRAINT FK_C6526B6BA76ED395');
        $this->addSql('ALTER TABLE user_permission_group DROP CONSTRAINT FK_C6526B6BB6C0CF1');
        $this->addSql('ALTER TABLE user_oauth_provider DROP CONSTRAINT FK_D93D2FD9A76ED395');
        $this->addSql('DROP TABLE permission');
        $this->addSql('DROP TABLE permission_group');
        $this->addSql('DROP TABLE permission_group_permission');
        $this->addSql('DROP TABLE user_permission_group');
        $this->addSql('DROP TABLE user_oauth_provider');
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('ALTER TABLE "user" DROP totp_secret');
        $this->addSql('ALTER TABLE "user" DROP is_two_factor_enabled');
        $this->addSql('ALTER TABLE "user" DROP backup_codes');
    }
}
